version: "3.8"

services:

  accounts:
    image: fhilips/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - fhilips-network

  loans:
    image: fhilips/loan:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - fhilips-network

  cards:
    image: fhilips/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - fhilips-network

networks:
  fhilips-network: null
